### ISSUE TITLE
Translate from confusable string to simple string?

### ISSUE THREAD

**Issue by guettli** [vhf/confusable_homoglyphs#4]
Thank you for this package.

I have this use case:
  
People accidentally insert unicode characters and area not aware of this.

I want to normalize the user input. See this StackOverflow question: http://stackoverflow.com/questions/43367355/translate-unicode-to-ascii-if-possible

I have not found a simple way to do this with your library.

... or I am on the wrong track here, and your library can't help me.

Thank you for sharing your code.

**Comment by vhf** [comment]
Hey!

I cannot comment on the StackOverflow question because I don't have 50 karma.

This comment is slightly off: https://stackoverflow.com/questions/43367355/translate-unicode-to-ascii-if-possible#comment73833814_43370118 because this lib doesn't provide 'best effort' or maintenance work to be up-to-date. It pulls the confusable glyphs directly from the list provided by the Unicode Consortium.

There's no simple way of doing what you'd like to do. You could rely on this lib to find e.g. all characters in a string that could be confused with LATIN script, and then replace each of them with the LATIN glyph with which it could be confused?

**Comment by AntoniosBarotsis** [comment]
Sorry for reviving this 5 years later 😅 

I'm working on my own library that sort of does this (mostly for fun but since I haven't seen many published alternatives I was thinking of publishing mine). 

I was wondering why, for replacing, you didn't just take the data from the [`confusables.txt`](http://www.unicode.org/Public/security/revision-03/confusables.txt) file and map any character that you find on the left, to the corresponding character on the right. Wouldn't this "normalize the user input"? Or am I missing something?

Thanks in advance!

**Comment by vhf** [comment]
> I was wondering why, for replacing, you didn't just take the data from the [confusables.txt](http://www.unicode.org/Public/security/revision-03/confusables.txt) file and map any character that you find on the left, to the corresponding character on the right. Wouldn't this "normalize the user input"? Or am I missing something?

There are edge cases IMO, for instance:
```
0049 ;	006C ;	SA	# ( I → l ) LATIN CAPITAL LETTER I → LATIN SMALL LETTER L	# 
```

**Comment by AntoniosBarotsis** [comment]
Oh I was unaware. I also see a mapping for "m" to "rn". I guess this was never the intended purpose hence cases like these. Anyway thanks for the reply!
